// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ComplaintRequest
{
    public Guid RequestId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? OrderItemId { get; set; }

    public string RequestType { get; set; }

    public string Reason { get; set; }

    public string MediaUrl { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public double? RefundAmount { get; set; }

    public string ReturnTrackingNumber { get; set; }

    public string ReturnShippingCarrier { get; set; }

    public DateTime? RefundedAt { get; set; }

    public Guid? ExchangeOrderId { get; set; }

    public string StaffNote { get; set; }

    public bool? CancelledByCustomer { get; set; }

    public virtual OrderItem OrderItem { get; set; }

    public virtual User User { get; set; }

    public virtual Order ExchangeOrder { get; set; }
}