// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Repositories.Models;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<ComplaintRequest> ComplaintRequests { get; set; }

    public virtual DbSet<Frame> Frames { get; set; }

    public virtual DbSet<FrameMedium> FrameMedia { get; set; }

    public virtual DbSet<LensFeature> LensFeatures { get; set; }

    public virtual DbSet<LensType> LensTypes { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Preorder> Preorders { get; set; }

    public virtual DbSet<PreorderItem> PreorderItems { get; set; }

    public virtual DbSet<Prescription> Prescriptions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    private string GetConnectionString()
    {
        IConfiguration configuration = new ConfigurationBuilder()
         .SetBasePath(Directory.GetCurrentDirectory())
         .AddJsonFile("appsettings.json", true, true).Build();
        return configuration["ConnectionStrings:DefaultConnection"];
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Only configure if no options (so DI registered options are respected)
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(GetConnectionString());
        }
    }
//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-B9R8VFQL;Initial Catalog=GlassesECommerce;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ComplaintRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__COMPLAIN__E3C5DE315445ED79");

            entity.ToTable("COMPLAINT_REQUEST");

            entity.Property(e => e.RequestId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("requestId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.MediaUrl)
                .HasColumnType("text")
                .HasColumnName("mediaUrl");
            entity.Property(e => e.OrderItemId).HasColumnName("orderItemId");
            entity.Property(e => e.Reason)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("reason");
            entity.Property(e => e.RequestType)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("requestType");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.OrderItem).WithMany(p => p.ComplaintRequests)
                .HasForeignKey(d => d.OrderItemId)
                .HasConstraintName("FK__COMPLAINT__order__6E01572D");

            entity.HasOne(d => d.User).WithMany(p => p.ComplaintRequests)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__COMPLAINT__userI__6D0D32F4");
        });

        modelBuilder.Entity<Frame>(entity =>
        {
            entity.HasKey(e => e.FrameId).HasName("PK__FRAME__36094A253B7E3885");

            entity.ToTable("FRAME");

            entity.Property(e => e.FrameId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("frameId");
            entity.Property(e => e.BasePrice).HasColumnName("basePrice");
            entity.Property(e => e.Brand)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("brand");
            entity.Property(e => e.BridgeWidth).HasColumnName("bridgeWidth");
            entity.Property(e => e.Color)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("color");
            entity.Property(e => e.FrameName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("frameName");
            entity.Property(e => e.FrameWidth).HasColumnName("frameWidth");
            entity.Property(e => e.LensWidth).HasColumnName("lensWidth");
            entity.Property(e => e.Material)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("material");
            entity.Property(e => e.Shape)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("shape");
            entity.Property(e => e.Size)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("size");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TempleLength).HasColumnName("templeLength");
        });

        modelBuilder.Entity<FrameMedium>(entity =>
        {
            entity.HasKey(e => e.MediaId).HasName("PK__FRAME_ME__D271B4625F2001E8");

            entity.ToTable("FRAME_MEDIA");

            entity.Property(e => e.MediaId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("mediaId");
            entity.Property(e => e.FrameId).HasColumnName("frameId");
            entity.Property(e => e.MediaType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mediaType");
            entity.Property(e => e.MediaUrl)
                .HasMaxLength(2048)
                .IsUnicode(false)
                .HasColumnName("mediaUrl");

            entity.HasOne(d => d.Frame).WithMany(p => p.FrameMedia)
                .HasForeignKey(d => d.FrameId)
                .HasConstraintName("FK__FRAME_MED__frame__49C3F6B7");
        });

        modelBuilder.Entity<LensFeature>(entity =>
        {
            entity.HasKey(e => e.FeatureId).HasName("PK__LENS_FEA__F4F118B38CFB822B");

            entity.ToTable("LENS_FEATURE");

            entity.Property(e => e.FeatureId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("featureId");
            entity.Property(e => e.ExtraPrice).HasColumnName("extraPrice");
            entity.Property(e => e.FeatureSpecification)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("featureSpecification");
            entity.Property(e => e.LensIndex).HasColumnName("lensIndex");
        });

        modelBuilder.Entity<LensType>(entity =>
        {
            entity.HasKey(e => e.LensTypeId).HasName("PK__LENS_TYP__B5251A59AF5152AC");

            entity.ToTable("LENS_TYPE");

            entity.Property(e => e.LensTypeId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("lensTypeId");
            entity.Property(e => e.ExtraPrice).HasColumnName("extraPrice");
            entity.Property(e => e.LensSpecification)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("lensSpecification");
            entity.Property(e => e.RequiresPrescription).HasColumnName("requiresPrescription");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__ORDERS__0809335D0F2AA51D");

            entity.ToTable("ORDERS");

            entity.Property(e => e.OrderId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("orderId");
            entity.Property(e => e.ArrivalDate)
                .HasColumnType("datetime")
                .HasColumnName("arrivalDate");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.ShippingAddress)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("shippingAddress");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TotalAmount).HasColumnName("totalAmount");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__ORDERS__userId__3E52440B");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PK__ORDER_IT__3724BD528CFD1628");

            entity.ToTable("ORDER_ITEM");

            entity.Property(e => e.OrderItemId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("orderItemId");
            entity.Property(e => e.FeatureId).HasColumnName("featureId");
            entity.Property(e => e.FrameId).HasColumnName("frameId");
            entity.Property(e => e.LensTypeId).HasColumnName("lensTypeId");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.OrderPrice).HasColumnName("orderPrice");
            entity.Property(e => e.PrescriptionId).HasColumnName("prescriptionId");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.SelectedColor)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("selectedColor");

            entity.HasOne(d => d.Feature).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.FeatureId)
                .HasConstraintName("FK__ORDER_ITE__featu__5629CD9C");

            entity.HasOne(d => d.Frame).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.FrameId)
                .HasConstraintName("FK__ORDER_ITE__frame__5535A963");

            entity.HasOne(d => d.LensType).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.LensTypeId)
                .HasConstraintName("FK__ORDER_ITE__lensT__571DF1D5");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__ORDER_ITE__order__534D60F1");

            entity.HasOne(d => d.Prescription).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.PrescriptionId)
                .HasConstraintName("FK__ORDER_ITE__presc__5441852A");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__PAYMENT__A0D9EFC609C3B2FC");

            entity.ToTable("PAYMENT");

            entity.Property(e => e.PaymentId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("paymentId");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasColumnName("paidAt");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("paymentMethod");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("paymentStatus");
            entity.Property(e => e.PreorderId).HasColumnName("preorderId");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__PAYMENT__orderId__6754599E");

            entity.HasOne(d => d.Preorder).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PreorderId)
                .HasConstraintName("FK__PAYMENT__preorde__68487DD7");
        });

        modelBuilder.Entity<Preorder>(entity =>
        {
            entity.HasKey(e => e.PreorderId).HasName("PK__PREORDER__923DB83C14CD373C");

            entity.ToTable("PREORDER");

            entity.Property(e => e.PreorderId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("preorderId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.ExpectedDate)
                .HasColumnType("datetime")
                .HasColumnName("expectedDate");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.Preorders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__PREORDER__userId__5BE2A6F2");
        });

        modelBuilder.Entity<PreorderItem>(entity =>
        {
            entity.HasKey(e => e.PreorderItemId).HasName("PK__PREORDER__80B22799F4EF8FAC");

            entity.ToTable("PREORDER_ITEM");

            entity.Property(e => e.PreorderItemId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("preorderItemId");
            entity.Property(e => e.FeatureId).HasColumnName("featureId");
            entity.Property(e => e.FrameId).HasColumnName("frameId");
            entity.Property(e => e.LensTypeId).HasColumnName("lensTypeId");
            entity.Property(e => e.PreorderId).HasColumnName("preorderId");
            entity.Property(e => e.PreorderPrice).HasColumnName("preorderPrice");
            entity.Property(e => e.PrescriptionId).HasColumnName("prescriptionId");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.SelectedColor)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("selectedColor");

            entity.HasOne(d => d.Feature).WithMany(p => p.PreorderItems)
                .HasForeignKey(d => d.FeatureId)
                .HasConstraintName("FK__PREORDER___featu__628FA481");

            entity.HasOne(d => d.Frame).WithMany(p => p.PreorderItems)
                .HasForeignKey(d => d.FrameId)
                .HasConstraintName("FK__PREORDER___frame__619B8048");

            entity.HasOne(d => d.LensType).WithMany(p => p.PreorderItems)
                .HasForeignKey(d => d.LensTypeId)
                .HasConstraintName("FK__PREORDER___lensT__6383C8BA");

            entity.HasOne(d => d.Preorder).WithMany(p => p.PreorderItems)
                .HasForeignKey(d => d.PreorderId)
                .HasConstraintName("FK__PREORDER___preor__5FB337D6");

            entity.HasOne(d => d.Prescription).WithMany(p => p.PreorderItems)
                .HasForeignKey(d => d.PrescriptionId)
                .HasConstraintName("FK__PREORDER___presc__60A75C0F");
        });

        modelBuilder.Entity<Prescription>(entity =>
        {
            entity.HasKey(e => e.PrescriptionId).HasName("PK__PRESCRIP__7920FC24AB33C185");

            entity.ToTable("PRESCRIPTION");

            entity.Property(e => e.PrescriptionId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("prescriptionId");
            entity.Property(e => e.AddLeft).HasColumnName("addLeft");
            entity.Property(e => e.AddRight).HasColumnName("addRight");
            entity.Property(e => e.AxisLeft).HasColumnName("axisLeft");
            entity.Property(e => e.AxisRight).HasColumnName("axisRight");
            entity.Property(e => e.ClinicName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("clinicName");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CylinderLeft).HasColumnName("cylinderLeft");
            entity.Property(e => e.CylinderRight).HasColumnName("cylinderRight");
            entity.Property(e => e.DoctorName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("doctorName");
            entity.Property(e => e.ExpirationDate)
                .HasColumnType("datetime")
                .HasColumnName("expirationDate");
            entity.Property(e => e.PupillaryDistance).HasColumnName("pupillaryDistance");
            entity.Property(e => e.SphereLeft).HasColumnName("sphereLeft");
            entity.Property(e => e.SphereRight).HasColumnName("sphereRight");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.Prescriptions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__PRESCRIPT__userI__4316F928");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__USER__CB9A1CFF30250E25");

            entity.ToTable("USER");

            entity.HasIndex(e => e.Email, "UQ__USER__AB6E6164A45F0E15").IsUnique();

            entity.Property(e => e.UserId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("userId");
            entity.Property(e => e.Address)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("fullName");
            entity.Property(e => e.PasswordHash)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("passwordHash");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("role");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}