// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class FrameMedium
{
    public Guid MediaId { get; set; }

    public Guid? FrameId { get; set; }

    public string MediaUrl { get; set; }

    public string MediaType { get; set; }

    public virtual Frame Frame { get; set; }
}