// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Frame
{
    public Guid FrameId { get; set; }

    public string FrameName { get; set; }

    public Guid? BrandId { get; set; }

    public Guid? MaterialId { get; set; }

    public int? LensWidth { get; set; }

    public int? BridgeWidth { get; set; }

    public int? FrameWidth { get; set; }

    public int? TempleLength { get; set; }

    public string Shape { get; set; }

    public string Size { get; set; }

    public double? BasePrice { get; set; }

    public string Status { get; set; }

    /// <summary>
    /// Current stock quantity available for sale
    /// </summary>
    public int? StockQuantity { get; set; }

    /// <summary>
    /// Minimum stock level before reorder/preorder is triggered
    /// </summary>
    public int? ReorderLevel { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Material Material { get; set; }

    public virtual ICollection<FrameSize> FrameSizes { get; set; } = new List<FrameSize>();

    public virtual ICollection<FrameColor> FrameColors { get; set; } = new List<FrameColor>();

    public virtual ICollection<FrameMedium> FrameMedia { get; set; } = new List<FrameMedium>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PreorderItem> PreorderItems { get; set; } = new List<PreorderItem>();

    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    public virtual ICollection<CampaignFrame> CampaignFrames { get; set; } = new List<CampaignFrame>();
}