// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Frame
{
    public Guid FrameId { get; set; }

    public string FrameName { get; set; }

    public string Brand { get; set; }

    public string Color { get; set; }

    public string Material { get; set; }

    public int? LensWidth { get; set; }

    public int? BridgeWidth { get; set; }

    public int? FrameWidth { get; set; }

    public int? TempleLength { get; set; }

    public string Shape { get; set; }

    public string Size { get; set; }

    public double? BasePrice { get; set; }

    public string Status { get; set; }

    public virtual ICollection<FrameMedium> FrameMedia { get; set; } = new List<FrameMedium>();

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PreorderItem> PreorderItems { get; set; } = new List<PreorderItem>();
}