// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class LensFeature
{
    public Guid FeatureId { get; set; }

    public double? LensIndex { get; set; }

    public string FeatureSpecification { get; set; }

    public double? ExtraPrice { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PreorderItem> PreorderItems { get; set; } = new List<PreorderItem>();
}