// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class LensType
{
    public Guid LensTypeId { get; set; }

    public string LensSpecification { get; set; }

    public bool? RequiresPrescription { get; set; }

    public double? BasePrice { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public Guid? BrandId { get; set; }

    public Guid? MaterialId { get; set; }

    public Guid? ColorId { get; set; }

    public string Status { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Material Material { get; set; }

    public virtual Color Color { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PreorderItem> PreorderItems { get; set; } = new List<PreorderItem>();

    public virtual ICollection<FrameLensType> FrameLensTypes { get; set; } = new List<FrameLensType>();
}