// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Order
{
    public Guid OrderId { get; set; }

    public Guid? UserId { get; set; }

    public double? TotalAmount { get; set; }

    public string ShippingAddress { get; set; }

    public DateTime? ArrivalDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string ShippingMethod { get; set; }

    public double? ShippingFee { get; set; }

    public string TrackingNumber { get; set; }

    public DateTime? ShippedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public string ShippingCarrier { get; set; }

    public Guid? ConvertedFromPreorderId { get; set; }

    public DateTime? EstimatedDeliveryDate { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }

    public DateTime? DeliveryConfirmedAt { get; set; }

    public virtual Preorder ConvertedFromPreorder { get; set; }
}