// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class OrderItem
{
    public Guid OrderItemId { get; set; }

    public Guid? OrderId { get; set; }

    public Guid? PrescriptionId { get; set; }

    public Guid? FrameId { get; set; }

    public Guid? FeatureId { get; set; }

    public Guid? LensTypeId { get; set; }

    public Guid? LensIndexId { get; set; }

    public int? Quantity { get; set; }

    public double? UnitPrice { get; set; }

    public Guid? SelectedColorId { get; set; }

    public string SelectedSize { get; set; }

    public virtual ICollection<ComplaintRequest> ComplaintRequests { get; set; } = new List<ComplaintRequest>();

    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();

    public virtual LensFeature Feature { get; set; }

    public virtual Frame Frame { get; set; }

    public virtual LensType LensType { get; set; }

    public virtual LensIndex LensIndex { get; set; }

    public virtual Order Order { get; set; }

    public virtual Prescription Prescription { get; set; }

    public virtual Color SelectedColor { get; set; }
}