// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public Guid? OrderId { get; set; }

    public Guid? PreorderId { get; set; }

    public double? Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual Preorder Preorder { get; set; }
}