// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PreorderItem
{
    public Guid PreorderItemId { get; set; }

    public Guid? PreorderId { get; set; }

    public Guid? PrescriptionId { get; set; }

    public Guid? FrameId { get; set; }

    public Guid? FeatureId { get; set; }

    public Guid? LensTypeId { get; set; }

    public int? Quantity { get; set; }

    public double? PreorderPrice { get; set; }

    public string SelectedColor { get; set; }

    public virtual LensFeature Feature { get; set; }

    public virtual Frame Frame { get; set; }

    public virtual LensType LensType { get; set; }

    public virtual Preorder Preorder { get; set; }

    public virtual Prescription Prescription { get; set; }
}