// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Preorder
{
    public Guid PreorderId { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? ExpectedDate { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public Guid? CampaignId { get; set; }

    public string AdminNotes { get; set; }

    public double? TotalAmount { get; set; }

    public virtual PreorderCampaign Campaign { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<PreorderItem> PreorderItems { get; set; } = new List<PreorderItem>();

    public virtual ICollection<PreorderStatusLog> StatusLogs { get; set; } = new List<PreorderStatusLog>();

    public virtual User User { get; set; }
}