// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Prescription
{
    public Guid PrescriptionId { get; set; }

    public Guid? UserId { get; set; }

    public double? SphereLeft { get; set; }

    public double? SphereRight { get; set; }

    public double? CylinderLeft { get; set; }

    public double? CylinderRight { get; set; }

    public int? AxisLeft { get; set; }

    public int? AxisRight { get; set; }

    public double? AddLeft { get; set; }

    public double? AddRight { get; set; }

    public int? PupillaryDistance { get; set; }

    public string DoctorName { get; set; }

    public string ClinicName { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<PreorderItem> PreorderItems { get; set; } = new List<PreorderItem>();

    public virtual User User { get; set; }
}